### ISSUE TITLE
Generic OAuth social button icon

### ISSUE THREAD

**Issue by nbarbettini** [stormpath/stormpath-widget#118]
When we allow people to create generic OAauth2 directories in IAMUI (soon), we'll end up with buttons that won't match one of the existing icons. Currently that results in an invisible button:

![screen shot 2017-02-03 at 3 50 30 pm](https://cloud.githubusercontent.com/assets/7525482/22613753/e2c83d2e-ea2f-11e6-921d-c19406c11a5f.png)

It'd be cool to get a generic/abstract icon that can be used if the widget doesn't recognize the directory type.

Later on, we could add more icons for common providers too :)

**Comment by nbarbettini** [comment]
Sounds good. I am going to implement the globe icon for now (thanks!) and close this. This will either come up quickly as a customer request, or people won't care. The workaround of supplying your own CSS style for whatever icon you need should be easy for now.

**Comment by dogeared** [comment]
We use the "lock" for generic SAML in the Java SDK.

[image: Inline image 1]

**Comment by nbarbettini** [comment]
@dogeared, your image didn't come through but your point is well taken. 😄 

@alexdahl, I wonder if it makes sense to have a different icon for SAML, since it's not really a provider we don't know but rather a provider we don't have any known icon at all for.

Not necessary to finalize for this pass, though!

**Comment by dogeared** [comment]
![image](https://cloud.githubusercontent.com/assets/364562/22672522/89d76738-eca2-11e6-9553-591e339592b0.png)

**Comment by nbarbettini** [comment]
@alexdahl Here's what I did: any provider type we don't recognize will fall back to this grey globe icon. This applies to SAML too, for now. We can opt to add a SAML icon and any other provider icons we want in the future, and it's always overridable by the dev as well. Slipped tooltips in there too. 👍 

<img src="http://g.recordit.co/OSsQP6rIKr.gif"/>
