### ISSUE TITLE
Example app Google login: update app name and redirects to localhost:3000

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-widget#134]
![image](https://cloud.githubusercontent.com/assets/364562/22696980/fbb81b1a-ed1d-11e6-870d-57384fc30708.png)

```http://localhost:3000/?jwtResponse=eyJraWQiOiJEOElJMU5WTFM2UjAwVFU5STA1QkdaS0RYIiwic3R0IjoiYXNzZXJ0aW9uIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJodHRwczovL2FwaS5zdG9ybXBhdGguY29tL3YxL2FjY291bnRzLzRrd2pjZFNDR0p5TklET2ExdEhWQkUiLCJqdGkiOiI2MGI0NGY5Yy0yMzU2LTRmY2EtOWZjMS1mMjNmZTdiYmIxN2EiLCJpc3MiOiJodHRwczovL2FwaS5zdG9ybXBhdGguY29tL3YxL2FwcGxpY2F0aW9ucy8xTU5rclpKOWZuVWs5cEZsbE5GNnVFIiwiYXVkIjoiRDhJSTFOVkxTNlIwMFRVOUkwNUJHWktEWCIsImlhdCI6MTQ4NjQ3NjgxNCwiZXhwIjoxNDg2NDc2ODc0LCJzdGF0dXMiOiJBVVRIRU5USUNBVEVEIiwiaXNOZXdTdWIiOnRydWUsImlydCI6ImEyNGM0YmYwLWIwYmYtNDRjZC05NWI4LTVmODI5NzBiNzNjOSJ9.arI4rq0C6fBVjishRkgugT2yjr07_u5CDiYe2XoigT4#```

**Comment by robertjd** [comment]
I see the localhost redirect when I authenticate w/ a google account that hasn't yet authorized this google application, but once I've done that, if I authenticate again, than I get redirected back to the demo app URL.  Are you seeing the same?
